services:
  postgres:
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
