services:
  globaldb:
    image: mysql
    ports:
      - 13000:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: globaldb

  logdb1:
    image: mysql
    ports:
      - 13001:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: logdb1

  logdb2:
    image: mysql
    ports:
      - 13002:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: logdb2

  logdb3:
    image: mysql
    ports:
      - 13003:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: logdb3
