services:
  postgres:
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  #maildev:
  #  build:
  #    context: .
  #    dockerfile: maildev.Dockerfile
  #  expose:
  #    - 1080
  #    - 1025

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   expose:
  #     - 6379

  api:
    build:
      context: .
      dockerfile: relational.e2e.Dockerfile
